library:
  source-dirs: src
tests:
  haskell-todolist-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-todolist
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- strict
- directory
- base >= 4.7 && < 5
name: haskell-todolist
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/haskell-todolist
license: BSD3
executables:
  haskell-todolist-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-todolist
description: Please see the README on GitHub at <https://github.com/githubuser/haskell-todolist#readme>
